IN_NIX_SHELL := env("IN_NIX_SHELL", "false")
BLOG_DIR := source_directory()

_default:
    @just --list

# PRIVATE COMMAND
# --------------------------------------------------

# Run Command in devShell
_blog-run cmd *args:
    #!/usr/bin/env -S sh -eu
    if [ "{{ IN_NIX_SHELL }}" = "false" ]; then
        cd {{ BLOG_DIR }} && nix develop "{{ BLOG_DIR }}"# --command {{ cmd }} {{ args }}
    else
        {{ cmd }} {{ args }}
    fi

# PUBLIC COMMAND
# --------------------------------------------------

# [B] build site
build:
  just _blog-run zola build

# [B] watch site and auto-build when detect change
watch:
  just _blog-run zola serve

# [B] Open neovim via Zellij layout
blog-edit:
  just _blog-run zellij --layout {{ BLOG_DIR }}/.zellij.kdl
