_blog-run COMMAND:
  nix develop .# --command sh -c "{{COMMAND}}"

blog-build:
  just _blog-run "zola build"

blog-watch:
  just _blog-run "zola serve"

blog-edit:
  zellij action new-tab --layout .zellij.kdl
