IN_NIX_SHELL := env("IN_NIX_SHELL", "false")
SOURCE_DIR := source_directory()

_default:
    @just --list

# PRIVATE COMMAND
# --------------------------------------------------

# Run Command in devShell
_source-run cmd *args:
    #!/usr/bin/env -S sh -eu
    if [ "{{ IN_NIX_SHELL }}" = "false" ]; then
        cd {{ SOURCE_DIR }} && nix develop "{{ SOURCE_DIR }}"# --command {{ cmd }} {{ args }}
    else
        {{ cmd }} {{ args }}
    fi

# PUBLIC COMMAND
# --------------------------------------------------

# [S] Auto-format the source tree
fmt:
   just _source-run treefmt

# [S] Run 'cargo run' on the project
run *ARGS:
    just _source-run cargo run {{ARGS}}

# [S] Run 'cargo build' on the project
build *ARGS:
    just _source-run cargo build {{ARGS}}

# [S] Run 'cargo watch' to run the project (auto-recompiles)
watch *ARGS:
    just _source-run cargo watch -x run -- {{ARGS}}

# [S] Open source code via Zellij layout
edit:
	just _source-run zellij -l {{ SOURCE_DIR }}/.zellij.kdl

